version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder
    container_name: sgblock-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000/api
      - VITE_CORE_VERSION=1.0.0
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - sgblock-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: sgblock-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://dev:dev@mongodb:27017/sgblock_dev?authSource=admin
      - JWT_SECRET=dev-secret-key-change-in-production
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:5173
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      - LOG_LEVEL=debug
    command: npm run dev
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sgblock-network

  mongodb:
    image: mongo:6.0
    container_name: sgblock-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=sgblock_dev
    volumes:
      - mongodb_dev_data:/data/db
      - ./backend/scripts/mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sgblock-network

  # Optional: MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: sgblock-mongo-express-dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dev
      - ME_CONFIG_MONGODB_URL=mongodb://dev:dev@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sgblock-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  sgblock-network:
    driver: bridge