version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: sgblock-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    image: sgblock-backend:dev
    container_name: sgblock-backend
    environment:
      - MONGO_URI=mongodb://root:changeme@mongo:27017
      - JWT_SECRET=supersecret
      - CORS_ORIGIN=http://localhost
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: sgblock-frontend:dev
    container_name: sgblock-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: sgblock-nginx:dev
    container_name: sgblock-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  mongo-data:
